version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/recordings.db:/app/recordings.db
    environment:
      - NODE_ENV=production

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
