services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_started
    networks:
      - app-network
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./database:/app/database
    environment:
      - NODE_ENV=docker
    networks:
      - app-network
networks:
  app-network:
    driver: bridge